=== mikiya1991/WSNEnvironmentMonitor/wsn-project-fin/wsn-project-fin/VISN-WSN/Node1/My Application/fp-mis_1_4.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
        DTD for MIS version 0x30 and higher.
-->

<!--
    An unsigned 8-bit integer 0-255.

    Also can be specified as hex by prefixing with "0x"
-->
<!ENTITY % Uint8 "CDATA">

<!--
    An unsigned, 16-bit integer 0-65535

    Also can be specified as hex by prefixing with "0x"
-->
<!ENTITY % Uint16 "CDATA">

<!--
    Channel type:

    ai - Analog Input
    ao - Analog Output
    di - Digital Input
    do - Digital Output
    ci - Counter Input
    co - Counter Output
    -->
<!ENTITY % ChanType "(ai|ao|di|do|ci|co|wfi|wfo|wii|wio|si|so)">

<!--
    Data type for attributes (enumerated or numerical)
    -->
<!ENTITY % DataType "(enum|u8|i8|u16|i16|u32|i32|f32)">

<!--
    Format for an integer.

    unsigned - unsigned int
    signed - 2's complement signed
    -->
<!ENTITY % IntFormat "(unsigned|signed)">

<!--
   LV Property Type

   none - None
   config - Config data
   channel - Channel data
   -->
<!ENTITY % LVPropType "(none|config|channel)">

<!--
   Node Architecture

   none - Not a node
   scrimmage - 3202, 3212
   peewee - 3226, etc
   varsity - 3214, etc
   -->
<!ENTITY % NodeArchitecture "(none|scrimmage|peewee|varsity)">

   <!--
    The top-level element for the MIS.  Attributes:

    version   An 8-bit version number for the MIS.
              Currently only 1 is supported.

    module-id The 16-bit unique ID for the module.

    hotswap-id The hot swap ID for the module, which is common
              between all modules that are register-compatible with
              this one

    semaphore-time semaphore request time, in microseconds,
              for this module.

    architecture product family for the node

    Sub-elements:

    name      Name of the module

    cis       One or more channel information sheets on the module's
              channels.
-->
<!ELEMENT mis (name, cis*)>
<!ATTLIST mis version %Uint8; #REQUIRED>
<!ATTLIST mis module-id %Uint16; #REQUIRED>
<!ATTLIST mis hotswap-id %Uint8; #REQUIRED>
<!ATTLIST mis semaphore-time %Uint8; #REQUIRED>
<!ATTLIST mis architecture %NodeArchitecture; #REQUIRED>
<!--
    String name used for any of the entities in the MIS.
    -->
<!ELEMENT name (#PCDATA)>

<!ELEMENT depth (#PCDATA)>
<!ELEMENT relaxedTimeStamp (#PCDATA)>

<!--
    Channel Information Sheet.  The information describing a
    group of like channels.  Attributes:

    reps        Number of logical channels described by
                this CIS.

    type        Type of channel

    points      Number of points (physical channels) per
                logical channel.

   lvprop      Type of LabVIEW property
    -->
<!ELEMENT cis (name, depth?, relaxedTimeStamp?, error*, range*, attr*, cmd*)>
<!ATTLIST cis id %Uint16; #REQUIRED>
<!ATTLIST cis reps %Uint8; #REQUIRED>
<!ATTLIST cis type %ChanType; #REQUIRED>
<!ATTLIST cis points %Uint8; #REQUIRED>
<!ATTLIST cis lvprop %LVPropType; #IMPLIED>

<!--
    Channel error description.  Attributes:

    id           Unique 8-bit ID for this error.
    -->
<!ELEMENT error (name)>
<!ATTLIST error id %Uint8; #REQUIRED>

<!--
    Element describing a channel range.  Attributes are:

    id          8-bit unique ID for the range
    unit        8-bit ID for the units of this range
                (see the CIS ID allocation document).

    Sub elements:
    low         Lower bound of the range in scaled units.

    high        Upper bound of the range in scaled units.

    default     Default value in raw counts.

    raw         Format of the raw value (unsigned is the default).

    type        Describes the size and format of the data.
    -->
<!ELEMENT range (low, high, default?)>
<!ATTLIST range id %Uint8; #REQUIRED>
<!ATTLIST range unit %Uint8; #REQUIRED>
<!ATTLIST range raw %IntFormat; #IMPLIED>
<!ATTLIST range type %DataType; #REQUIRED>

<!--
    Lower bound of the range.  Attributes:

    -->
<!ELEMENT low (#PCDATA)>

<!--
    Upper bound of the range.  Attributes:

    -->
<!ELEMENT high (#PCDATA)>

<!--
    Default value for the range or attr/command.

    -->
<!ELEMENT default (#PCDATA)>

<!--
    Attribute element.

    type        Describes the size and format of the data.
    id          Unique 8-bit ID for the attribute.

    length      Length, in bytes, of a multi-byte attribute.
                This only needs to be specified if this attribute
                is the first byte of a multi-byte attribute.
                May be omitted for single-byte attributes or
                subsequent bytes of multi-byte attributes.
-->
<!ELEMENT attr (name, ((low, high) | enum), default)>
<!ATTLIST attr type %DataType; #REQUIRED>
<!ATTLIST attr id %Uint8; #REQUIRED>
<!ATTLIST attr length %Uint8; #IMPLIED>

<!--
    Minimum value for this attribute/command as
    an 8-bit integer.  Prefixing with "0x"
    will cause it to be interpreted as hex
    -->
<!ELEMENT min (#PCDATA)>

<!--
    Maximum value for this attribute/command as
    an 8-bit integer.  Prefixing with "0x"
    will cause it to be interpreted as hex
    -->
<!ELEMENT max (#PCDATA)>

<!--
    Collection of enumerated elements in an
    enumerated command or attribute.
    -->
<!ELEMENT enum (enum-element*)>

<!--
    Element of an enumerated command or attribute.

    id     The 8-bit value for this enumerated element.
    -->
<!ELEMENT enum-element (name)>
<!ATTLIST enum-element id %Uint8; #REQUIRED>

<!--
    Command element.

    id          Unique 8-bit ID for the attribute.

    length      Length, in bytes, of a multi-byte command.
                This only needs to be specified if this command
                is the first byte of a multi-byte command.
                May be omitted for single-byte command or
                subsequent bytes of multi-byte commands.
-->
<!ELEMENT cmd (name, ((min, max) | enum))>
<!ATTLIST cmd id %Uint8; #REQUIRED>
<!ATTLIST cmd length %Uint8; #IMPLIED>

=== mikiya1991/WSNEnvironmentMonitor/wsn-project-fin/wsn-project-fin/VISN-WSN/Node1/My Application/WSN-3202.xml
<?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE mis SYSTEM "fp-mis_1_4.dtd">
    <!-- Copyright : National Instruments 2011.  All Rights Reserved.  -->
    <!-- Access    : By NI EULA Only, otherwise Company Confidential        -->
    <!-- MIS is made from several CIS -->
<mis version="0x40" hotswap-id="0x62" module-id="0x0162" semaphore-time="20" architecture="scrimmage">
    <name>NI WSN-3202</name>
    <!-- =====================================================      IO Specific Channels    ======================================================= -->
    <!-- 4 AI Voltage channels -->
    <cis type="ai" id="0x6200" reps="4" points="1" lvprop="config">
        <name>AI</name>
        <depth>2</depth>
        <range unit="0x04" id="0x03" type="f32">
            <low>-10</low>
            <high>+10</high>
        </range>
        <range unit="0x04" id="0x05" type="f32">
            <low>-5</low>
            <high>+5</high>
        </range>
        <range unit="0x04" id="0x82" type="f32">
            <low>-2</low>
            <high>+2</high>
        </range>
        <range unit="0x04" id="0x83" type="f32">
            <low>-0.500</low>
            <high>+0.500</high>
        </range>
        <attr type="enum" id="0x04">
            <name>Sensor Power</name>
            <enum>
                <enum-element id="1">
                    <name>0ms Before Sampling</name>
                </enum-element>
                <enum-element id="2">
                    <name>25ms Before Sampling</name>
                </enum-element>
                <enum-element id="3">
                    <name>100ms Before Sampling</name>
                </enum-element>
                <enum-element id="4">
                    <name>250ms Before Sampling</name>
                </enum-element>
                <enum-element id="0xFE">
                    <name>Always On</name>
                </enum-element>
            </enum>
            <default>1</default>
        </attr>
    </cis>
    <!-- 4 DIO channels  (DI is always valid.  DO may be ignored depending on the DIO Drive Mode)-->
    <cis id="0x6101" points="1" reps="4" type="di">
        <name>__config__DI</name>
        <depth>2</depth>
        <range unit="0" id="0x10" type="u8">
            <low>0</low>
            <high>1</high>
            <default>0</default>
        </range>
    </cis>
    <cis id="0x6102" points="1" reps="4" type="do" lvprop="config">
        <name>DIO</name>
        <depth>2</depth>
        <range unit="0" id="0x10" type="u8">
            <low>0</low>
            <high>1</high>
            <default>0</default>
        </range>
        <attr type="enum" id="0x20">
            <name>DIO Drive Mode</name>
            <enum>
                <enum-element id="0">
                    <name>Tristate</name>
                </enum-element>
                <enum-element id="1">
                    <name>Drive Low Only</name>
                </enum-element>
                <enum-element id="2">
                    <name>Drive High Only</name>
                </enum-element>
                <enum-element id="3">
                    <name>Drive High and Low</name>
                </enum-element>
            </enum>
            <default>0</default>
        </attr>
    </cis>
    <!-- =====================================================           WSN Common Channels           All WSN Nodes share the following channels.           IMPORTANT!!! - This channels must remain at the end           of the MIS.  New channels are added to the top. The           bluebus driver relies on this ordering to locate           node configuration information. ======================================================= -->
    <!-- Sample Rate in Seconds-->
    <cis type="ao" id="0x6300" reps="1" points="1" lvprop="channel">
        <name>__config__Sample Interval</name>
        <depth>1</depth>
        <relaxedTimeStamp>1</relaxedTimeStamp>
        <range unit="0x08" id="0x81" type="f32">
            <low>0.1</low>
            <high>100000.0</high>
            <default>5</default>
        </range>
    </cis>
    <!-- The Heartbeat Rate in Seconds-->
    <cis type="ao" id="0x6301" reps="1" points="1">
        <name>__config__Heartbeat</name>
        <depth>1</depth>
        <relaxedTimeStamp>1</relaxedTimeStamp>
        <range unit="0x08" id="0x81" type="f32">
            <low>0.1</low>
            <high>90.0</high>
            <default>61</default>
        </range>
    </cis>
    <!-- The battery level is sent as a normal AI channel back to LV Host-->
    <cis type="ai" id="0x6302" reps="1" points="1">
        <name>Battery Voltage</name>
        <depth>2</depth>
        <relaxedTimeStamp>1</relaxedTimeStamp>
        <range unit="0x04" id="0x04" type="f32">
            <low>0</low>
            <high>10</high>
        </range>
    </cis>
    <!-- The Link Quality is sent as a normal AI channel back to LV Host-->
    <cis type="ai" id="0x6303" reps="1" points="1">
        <name>Link Quality</name>
        <depth>2</depth>
        <relaxedTimeStamp>1</relaxedTimeStamp>
        <range unit="0x0E" id="0x38" type="f32">
            <low>0</low>
            <high>100</high>
        </range>
    </cis>
    <!-- "VI on the Node" indicates whether the node is running LV.  It is a normal Digital Input channel.-->
    <cis id="0x6304" points="1" reps="1" type="di">
        <name>VI Deployed</name>
        <depth>2</depth>
        <relaxedTimeStamp>1</relaxedTimeStamp>
        <range unit="0" id="0x10" type="u8">
            <low>0</low>
            <high>1</high>
            <default>0</default>
        </range>
    </cis>
    <!-- "External Power" indicates whether the node is running on external power or batteries.  It is a normal Digital Input channel.-->
    <cis id="0x6305" points="1" reps="1" type="di">
        <name>External Power</name>
        <depth>2</depth>
        <relaxedTimeStamp>1</relaxedTimeStamp>
        <range unit="0" id="0x10" type="u8">
            <low>0</low>
            <high>1</high>
            <default>0</default>
        </range>
    </cis>
    <!-- "Mesh Router" indicates whether the node is using routing firmware or end node firmware in the radio.  It is a normal Digital Input channel.-->
    <cis id="0x6306" points="1" reps="1" type="di">
        <name>Mesh Router</name>
        <depth>2</depth>
        <relaxedTimeStamp>1</relaxedTimeStamp>
        <range unit="0" id="0x10" type="u8">
            <low>0</low>
            <high>1</high>
            <default>0</default>
        </range>
    </cis>
    <!-- User Defined Variables -->

</mis>
